const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
function app(){
 let counter=0,lock=false,failCalendar=false;
 const sheets={};class Sheet{constructor(){this.rows=[];}getLastRow(){return this.rows.length;}appendRow(r){this.rows.push(r);return this;}setName(){return this;}getRange(row,col,n=1,m=1){return {getValues:()=>this.rows.slice(row-1,row-1+n).map(r=>r.slice(col-1,col-1+m)),setValue:v=>{this.rows[row-1]||=[];this.rows[row-1][col-1]=v;},setValues:vs=>vs.forEach((v,i)=>{this.rows[row-1+i]=v;})};}}
 for(const n of ['Bookings','Access','Issues'])sheets[n]=new Sheet();
 sheets.Bookings.appendRow(['JSON']);sheets.Access.appendRow(['label','code','enabled']).appendRow(['A','a'.repeat(32),true]).appendRow(['B','b'.repeat(32),true]);
 const now=Date.parse('2026-09-28T10:00:00-07:00');const NativeDate=Date;class FakeDate extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 function event(id,hour,capacity){let desc='Capacity: '+capacity+'\nBooking: open';return {getId:()=>id,getStartTime:()=>new NativeDate('2026-09-28T'+hour+':00:00-07:00'),getEndTime:()=>new NativeDate('2026-09-28T'+hour+':30:00-07:00'),getTitle:()=>id,getLocation:()=>'',isAllDayEvent:()=>false,isRecurringEvent:()=>false,getDescription:()=>desc,setDescription:d=>{if(failCalendar)throw Error('calendar failed');desc=d;}};}
 const evs=[event('s1',16,1),event('s2',18,4)],p={CALENDAR_ID:'cal',LEDGER_ID:'ledger'};
 const c={Intl,Date:FakeDate,Set,console,PropertiesService:{getScriptProperties:()=>({getProperty:k=>p[k]})},Session:{getActiveUser:()=>({getEmail:()=>''})},LockService:{getScriptLock:()=>({waitLock:()=>{assert.equal(lock,false);lock=true;},releaseLock:()=>{lock=false;}})},SpreadsheetApp:{openById:()=>({getSheetByName:n=>sheets[n]}),flush(){}},CalendarApp:{getCalendarById:()=>({getEvents:()=>evs,getEventById:id=>evs.find(e=>e.getId()===id)})},Utilities:{getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(alg,s)=>[...crypto.createHash('sha256').update(s).digest()]},MailApp:{}};
 vm.createContext(c);for(const f of ['Rules.gs','Code.gs'])vm.runInContext(fs.readFileSync(__dirname+'/../src/'+f,'utf8'),c);
 function req(action,extra={},code='a'.repeat(32)){return c.request({code,action,requestId:'request-'+(++counter)+'-xxxxxxxx',...extra});}
 const view=code=>req('view',{},code).data;
 return {c,req,view,evs,fail:v=>failCalendar=v,records:()=>c.read_()};
}
test('end-to-end booking, final seat exclusion, cancellation and ownership',()=>{const a=app();let s=a.view().slots[0];const r=a.req('reserve',{slotId:s.id,revision:s.revision,names:['Anita']});assert.equal(r.ok,true);assert.equal(r.pending,false);assert.match(a.evs[0].getDescription(),/Anita/);assert.equal(a.view().slots.length,1);assert.equal(a.req('cancel',{bookingId:r.data.bookings[0].id},'b'.repeat(32)).ok,false);const cancel=a.req('cancel',{bookingId:r.data.bookings[0].id});assert.equal(cancel.ok,true);assert.equal(a.view().slots.length,2);});
test('request idempotency returns same reservation',()=>{const a=app(),s=a.view().slots[1],p={slotId:s.id,revision:s.revision,names:['Anita'],requestId:'same-request-xxxxxxxx'};a.req('reserve',p);a.req('reserve',p);assert.equal(a.records().length,1);});
test('failed calendar write reserves capacity but is not confirmed; retry recovers',()=>{const a=app(),s=a.view().slots[0];a.fail(true);const r=a.req('reserve',{slotId:s.id,revision:s.revision,names:['Anita']});assert.equal(r.pending,true);assert.equal(a.view().slots.length,1);a.fail(false);a.c.settle_(a.records()[0]);assert.equal(a.records()[0].state,'confirmed');});
test('failed reschedule keeps original; successful retry releases it',()=>{const a=app(),ss=a.view().slots;const r=a.req('reserve',{slotId:ss[0].id,revision:ss[0].revision,names:['Anita']});a.fail(true);const moved=a.req('reschedule',{bookingId:r.data.bookings[0].id,slotId:ss[1].id,revision:ss[1].revision});assert.equal(moved.pending,true);assert.equal(a.records()[0].state,'confirmed');a.fail(false);a.c.settle_(a.records()[1]);assert.equal(a.records()[0].state,'cancelled');assert.equal(a.records()[1].state,'confirmed');});
test('invalid codes, unexpected actions and setup privilege denied',()=>{const a=app();assert.equal(a.req('view',{},'bad').ok,false);assert.equal(a.req('setup').ok,false);assert.throws(()=>a.c.setup(),/leader/);});
test('stale session revision cannot confirm',()=>{const a=app();assert.equal(a.req('reserve',{slotId:'s1',revision:'stale',names:['Anita']}).ok,false);});
test('each leader notice remains queued even when booking is cancelled before email',()=>{const a=app(),s=a.view().slots[0];const r=a.req('reserve',{slotId:s.id,revision:s.revision,names:['Anita']});a.req('cancel',{bookingId:r.data.bookings[0].id});const subjects=a.records()[0].notifications.map(n=>n.subject);assert.equal(subjects.length,2);assert.equal(subjects[0],'New booking');assert.equal(subjects[1],'Cancellation');});
test('reschedule cannot move to a full destination and keeps original',()=>{const a=app(),ss=a.view().slots;const old=a.req('reserve',{slotId:ss[0].id,revision:ss[0].revision,names:['Anita']});a.req('reserve',{slotId:ss[1].id,revision:ss[1].revision,names:['Mina','Ravi','Zoya','Hari']},'b'.repeat(32));const r=a.req('reschedule',{slotId:ss[1].id,revision:ss[1].revision,bookingId:old.data.bookings[0].id});assert.equal(r.ok,false);assert.equal(a.records()[0].state,'confirmed');});
test('revoked identities cannot change or view bookings',()=>{const a=app();assert.equal(a.req('view',{},'c'.repeat(32)).ok,false);});
